name: github_engineering_analytics
version: "1.0.0"
config-version: 2

profile: github_engineering_analytics

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  github_engineering_analytics: {}
