[project]
name = "github_engineering_analytics"
version = "0.0.1"
authors = [{ name = "pepijnsch@gmail.com" }]
requires-python = ">=3.12,<3.13"
dependencies = [
    # Any dependencies for jobs and pipelines in this project can be added here
    # See also https://docs.databricks.com/dev-tools/bundles/library-dependencies
    #
    # LIMITATION: for pipelines, dependencies are cached during development;
    # add dependencies to the 'environment' section of your pipeline.yml file instead
    "requests>=2.34.2",
    "tenacity>=9.1.4",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "databricks-dlt",
    "databricks-connect>=16.4,<16.5",
    "ipykernel",
    "pytest-mock>=3.15.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
target-version = "py312"
line-length = 88
respect-gitignore = true
show-fixes = true
unsafe-fixes = false

[tool.ruff.lint]
select = [
    "E", "F", "I", "UP"
]

[tool.ruff.lint.isort]
known-first-party = ["github_engineering_analytics"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "integration: requires Databricks Connect and a dedicated DEV catalog",
]
