[project]
name = "github_engineering_analytics"
version = "0.0.2"
authors = [{ name = "pepijnsch@gmail.com" }]
requires-python = ">=3.12,<3.13"
dependencies = [
    "loguru>=0.7.3",
    # Any dependencies for jobs and pipelines in this project can be added here
    # See also https://docs.databricks.com/dev-tools/bundles/library-dependencies
    #
    # LIMITATION: for pipelines, dependencies are cached during development;
    # add dependencies to the 'environment' section of your pipeline.yml file instead
    "requests>=2.34.2",
    "tenacity>=9.1.4",
]

[project.scripts]
github-engineering-analytics-full-load = "github_engineering_analytics.bronze.full_load:main"


[dependency-groups]
dev = [
    "bump-my-version>=1.5.1",
    "pytest",
    "ruff",
    "databricks-dlt",
    "databricks-connect>=16.4,<16.5",
    "ipykernel",
    "pytest-mock>=3.15.1",
]

[tool.bumpversion]
current_version = "0.0.2"
allow_dirty = false
commit = true
message = "chore(release): v{new_version}"
tag = true
tag_name = "v{new_version}"
tag_message = "Release v{new_version}"
push_tag = false
pre_commit_hooks = ["uv lock --offline"]

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "uv.lock"
search = '''name = "github-engineering-analytics"
version = "{current_version}"'''
replace = '''name = "github-engineering-analytics"
version = "{new_version}"'''

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
target-version = "py312"
line-length = 88
respect-gitignore = true
show-fixes = true
unsafe-fixes = false

[tool.ruff.lint]
select = [
    "E", "F", "I", "UP"
]

[tool.ruff.lint.isort]
known-first-party = ["github_engineering_analytics"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "integration: requires Databricks Connect and a dedicated DEV catalog",
]
